### ISSUE TITLE
'Réduction' column to be selectable

### ISSUE THREAD

**Issue by dvergeylen** [maieul/facture#3]
Hello,

Thank you for this very good package.

Unfortunately, it isn't possible to hide the "Remise" column when no reduction is applied. I tried to hack to source code myself but it seems the headers columns and lines generated aren't aligned anymore.

It would be very nice to have an option to set it (in)visible.

Have a nice day,
Daniel.

**Comment by maieul** [comment]
please try version on branch "issue3". It provides an option "noreduction" to disable this column.

**Comment by dvergeylen** [comment]
I'm afraid I only see two branches (master and laregurs), am I missing something? :-(

Can you provide a link?

I am french speaking if it's more convenient to you.

**Comment by maieul** [comment]
désolé, j'avais oublié d'envoyer la branche sur le serveur. Vous devriez la trouver maintenant. Il vous faut compiler le fichier .ins pour produire le fichier .cls.

**Comment by dvergeylen** [comment]
J'ai compilé via make, il ne trouvait pas bidi.sty, j'ai fourni celui de lualatex, apparemment cela a suffit:
/usr/share/texlive/texmf-dist/tex/lualatex/luabidi/luabidi.sty

Super l'exemple sans remise, si je comprends bien il suffit de mettre l'option [sansremise] dans documentclass, est-ce correct?

Daniel.

**Comment by maieul** [comment]
oui, c'est cela.

**Comment by maieul** [comment]
si tout fonctionne, me le signaler, je publierai sur le ctan

**Comment by dvergeylen** [comment]
L'exemple que vous avez donné fonctionne en effet chez moi :+1:

**Comment by maieul** [comment]
ok, je publie alors
