### ISSUE TITLE
Le taux normal de TVA est à 20%

### ISSUE THREAD

**Issue by quark67** [maieul/facture#4]
Depuis 2014, le taux normal de TVA est à 20% en France, au lieu de 19,6%.
Sources : 
https://fr.wikipedia.org/wiki/Taxe_sur_la_valeur_ajoutée_en_France
http://vosdroits.service-public.fr/professionnels-entreprises/F23567.xhtml

Je pense qu'il serait bon de mettre à jour.
Peut-être même conviendrait-il de définir des clés (superRed, reduit, intermed, normal , ou s, r, i, n, et éventuellement "z" s'il existe des produits ou services non taxés) pour le paramètre <taux de TVA> plutôt que d'avoir à entrer chaque fois la valeur (en conservant cette possibilité pour des cas particuliers). 

C'est un peu hors sujet (peut-être conviendrait-il mieux d'ouvrir un autre "issue", je le ferais sur demande), mais je suis surpris par l'alignement des différents éléments dans macros/xetex/latex/facture/exemple.pdf. C'est peut être voulu, mais ça fait bizarre je trouve. Ainsi, il semble que le tableau débute par la même indentation que le texte qui le suit, tandis que les totaux vont dans la marge droite. Est-ce une pratique courante dans le monde de la facturation ?

**Comment by maieul** [comment]
en fait j'ai maintenu le taux à 19,6 pour éviter que si des personnes ayant perdu le PDF recompile avec le taux à 20 il se retrouve avec une augmentation du prix ttc. 

effectivement l'idée de catégorie est pas mal, mais je t'avoue que le développement de cette classe n'est pas dans mes priorités du moment… donc je ne vais pas passer du temps dessus. Cette classe au départ était juste là pour répondre à mes propres besoins.

quant aux alignements, c'est juste que ma classe est degeulasse, faite à l'arrache. cela vaudrait effectivement la peine d'être réglée. Du reste il faut que je règle un bug dans la tailel des cellules depuis la version 1.1 (@joelgombin ?)=

**Comment by joelgombin** [comment]
@maieul, tu sais que mes capacités de développement en latex sont très, très limitées...

**Comment by maieul** [comment]
oui je sais, et en plus c'est moi le coupable, d'après git ce3acb5d6afc28be54afc86a200cdd4374b50ef6=

**Comment by maieul** [comment]
concernant les alignements, j'ai créé une branche 1.2.1. Elle corrige plusieurs problèmes d'alignement. En particulier, elle tient en compte l'espacement inter-colonne pour la largeur des colonnes. 

Désormais la taille laissé pour l'affichage des chiffres est calculé automatiquement à partir de la largeur du descriptif et de la taille alloué à l'indication de la TVA. Ainsi on a un tableau qui fait systèmatiquement la largeur totale de la page (évidemment on peut surcharger ce calcul, mais ce n'est pas conseillé).

J'ai aussi géré l'alignement de l'entête et des totaux.=

**Comment by maieul** [comment]
bon, qu1 pour tester cette branche 1.2.1 où je publie tel quel? j'ajouterai un note pour expliquer pourquoi la TVA ne change pas d'une fois sur l'autre. et concernant les catégories, ouvrir un nouveau ticket ...
