### ISSUE TITLE
La compilation échoue si `\numero` n'est pas défini

### ISSUE THREAD

**Issue by a3nm** [maieul/facture#7]
Si je prends le fichier exemple.tex du dépôt, supprime la ligne `\numero{24}` et que je compile, j'obtiens l'erreur suivante :

```
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.27 \entete
```
            
Il faudrait sans doute déplacer le retour à la ligne après `\ifdef{\@numero}{%` pour qu'il soit à l'intérieur du test.

**Comment by maieul** [comment]
merci, je viens de corriger et d'envoyer sur le CTAN.

**Comment by a3nm** [comment]
Ça marche pour moi, merci beaucoup !
