### ISSUE TITLE
Pas de Makefile ou d'explications sur comment compiler

### ISSUE THREAD

**Issue by a3nm** [maieul/facture#8]
Ce serait bien d'avoir un Makefile pour que ce soit facile de préparer la documentation en PDF et le fichier .cls à partir d'un clone du dépôt. Par exemple en adaptant https://github.com/PierreSenellart/apxproof/blob/master/Makefile

**Comment by maieul** [comment]
il y a un makefile :p

**Comment by maieul** [comment]
https://github.com/maieul/facture/blob/master/makefile

**Comment by a3nm** [comment]
Woaw, comment ai-je fait pour rater ça... Vraiment désolé pour le bruit.
:/

-- 
Antoine Amarilli
