### ISSUE TITLE
Nouvelle mention obligatoire : "dispensé d'immatriculation"

### ISSUE THREAD

**Issue by el-dge** [maieul/facture#9]
Le numéro de SIREN doit, dans le cas spécifique des auto-entrepreneurs dispensés d’immatriculation, être suivi immédiatement et lisiblement de la mention :
– pour le commerçant : «dispensé d’immatriculation en application de l’article L.123-1-1 du Code de commerce»,
– pour l’artisan : «dispensé d’immatriculation en application du V de l’article 19 de la loi n°96-603 du 5 juillet 1996 relative au développement du commerce et de l’artisanat» ;

**Comment by maieul** [comment]
la commande \pied permet deja de mettre ce qu’on veut en pied  (SIREN, mais aussi phrase de ce type)

**Comment by el-dge** [comment]
Merci pour ta réponse très rapide.
D'accord, mais comme c'est obligatoire, je pensais que l'intégré dans ton code n'était pas une mauvaise idée. Mais ok.

**Comment by maieul** [comment]
non car le modèle peut s’appliquer à d’autres pays
